//! ffmpeg + GPU gated integration test for the streaming playback render loop
//! (`playback::RenderLoop`).
//!
//! Builds a short video clip (and a two-track variant), drives the render loop's
//! `render_frame` directly (no thread/clock so the test is deterministic), and
//! asserts it composites real, non-black, animating frames and survives a seek.
//!
//! Gated behind the `playback-engine` feature (the module only exists then) AND
//! auto-skips when ffmpeg/ffprobe are missing or no GPU adapter is available, so
//! the default `cargo test` stays green offline. Nothing is downloaded — fixtures
//! are generated by ffmpeg's lavfi `testsrc`.
#![cfg(feature = "playback-engine")]

use std::path::Path;
use std::process::Command;
use std::sync::atomic::{AtomicI32, AtomicUsize, Ordering};
use std::sync::Arc;
use std::thread::sleep;
use std::time::Duration;

use opentake_domain::{
    Clip, ClipType, MediaManifest, MediaManifestEntry, MediaSource, Timeline, Track,
};
use opentake_render::{DecodedFrame, RenderSize};
use opentake_tauri_lib::playback::{
    project_media, project_text, FrameSink, InstantClock, PlaybackClock, PlaybackEngine,
    PlayheadEmitter, RenderLoop,
};

/// Warm-up budget: the decode worker is a separate thread/process, so the first
/// `render_frame(target)` can be black until ffmpeg produces that frame. 200 ×
/// 10ms = ~2s, ample for a 320×240 `testsrc` frame.
const WARMUP_TRIES: usize = 200;
const WARMUP_SLEEP: Duration = Duration::from_millis(10);

fn ffmpeg_ready() -> bool {
    Command::new("ffmpeg")
        .arg("-version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Generate an N-frame `testsrc` video at `path`. Returns false (→ skip) on
/// failure. `hue` shifts the palette so two assets differ visibly.
fn make_video(path: &Path, w: u32, h: u32, fps: u32, frames: u32, hue: i32) -> bool {
    let dur = frames as f64 / fps as f64;
    Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            &format!("testsrc=duration={dur}:size={w}x{h}:rate={fps}"),
            "-vf",
            &format!("hue=h={hue}"),
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-y",
        ])
        .arg(path)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

fn external_entry(id: &str, path: &Path, w: i32, h: i32, fps: f64) -> MediaManifestEntry {
    MediaManifestEntry {
        id: id.into(),
        name: format!("{id}.mp4"),
        kind: ClipType::Video,
        source: MediaSource::External {
            absolute_path: path.to_string_lossy().into_owned(),
        },
        duration: 1.0,
        generation_input: None,
        source_width: Some(w),
        source_height: Some(h),
        source_fps: Some(fps),
        has_audio: Some(false),
        folder_id: None,
        cached_remote_url: None,
        cached_remote_url_expires_at: None,
    }
}

/// Build a `RenderLoop`, mapping a `no GPU device` error to `None` (→ skip).
fn try_render_loop(
    timeline: Timeline,
    manifest: &MediaManifest,
    render_size: RenderSize,
) -> Option<RenderLoop> {
    let (sizes, media) = project_media(manifest, &None);
    let text = project_text(&timeline);
    match RenderLoop::new(timeline, media, text, sizes, render_size) {
        Ok(rl) => Some(rl),
        Err(e) if e.contains("no GPU device") => {
            eprintln!("skip: no GPU adapter available ({e})");
            None
        }
        Err(e) => panic!("render loop init failed: {e}"),
    }
}

/// Render `target` repeatedly until the frame has any non-zero pixel (decode
/// warmed up) or the budget is exhausted. Returns the non-black frame's RGBA.
fn render_until_content(rl: &mut RenderLoop, target: i32, w: u32, h: u32) -> Option<Vec<u8>> {
    for _ in 0..WARMUP_TRIES {
        let f = rl.render_frame(target).expect("render_frame");
        assert_eq!(f.width, w, "composite width matches render size");
        assert_eq!(f.height, h, "composite height matches render size");
        if f.rgba.iter().any(|&b| b != 0) {
            return Some(f.rgba);
        }
        sleep(WARMUP_SLEEP);
    }
    None
}

#[test]
fn render_loop_streams_frames_advances_and_seeks() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let src = dir.path().join("src.mp4");
    let (w, h, fps, frames) = (320u32, 240u32, 10u32, 12u32);
    if !make_video(&src, w, h, fps, frames, 0) {
        eprintln!("skip: could not generate fixture media");
        return;
    }

    let mut tl = Timeline::new();
    tl.fps = fps as i32;
    let mut track = Track::new("t1", ClipType::Video);
    track
        .clips
        .push(Clip::new("clip-1", "asset-1", 0, frames as i32));
    tl.tracks.push(track);
    let mut manifest = MediaManifest::new();
    manifest.entries.push(external_entry(
        "asset-1", &src, w as i32, h as i32, fps as f64,
    ));

    let size = RenderSize::new(w, h);
    let Some(mut rl) = try_render_loop(tl, &manifest, size) else {
        return;
    };
    assert_eq!(rl.total_frames(), frames as i32);
    assert_eq!(rl.fps(), fps as i32);

    // Frame 0 composites real content (not the clear color).
    let frame0 = render_until_content(&mut rl, 0, w, h)
        .expect("frame 0 should composite non-black within the warm-up budget");

    // A later frame differs (testsrc animates a moving pattern + timestamp).
    let mut differs = false;
    for _ in 0..WARMUP_TRIES {
        let f = rl.render_frame(8).expect("render_frame(8)");
        if f.rgba.iter().any(|&b| b != 0) && f.rgba != frame0 {
            differs = true;
            break;
        }
        sleep(WARMUP_SLEEP);
    }
    assert!(differs, "a later frame should differ from frame 0");

    // Seek restarts the decode streams and still composites frame 0.
    rl.seek();
    let after_seek = render_until_content(&mut rl, 0, w, h)
        .expect("frame 0 should composite again after a seek");
    assert!(after_seek.iter().any(|&b| b != 0));
}

#[test]
fn render_loop_composites_two_tracks_concurrently() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let src_a = dir.path().join("a.mp4");
    let src_b = dir.path().join("b.mp4");
    let (w, h, fps, frames) = (320u32, 240u32, 10u32, 12u32);
    // Two visibly different sources (hue-shifted) to exercise two concurrent,
    // independently-keyed (by clip id) decode streams.
    if !make_video(&src_a, w, h, fps, frames, 0) || !make_video(&src_b, w, h, fps, frames, 120) {
        eprintln!("skip: could not generate fixture media");
        return;
    }

    let mut tl = Timeline::new();
    tl.fps = fps as i32;
    let mut t1 = Track::new("t1", ClipType::Video);
    t1.clips
        .push(Clip::new("clip-1", "asset-1", 0, frames as i32));
    let mut t2 = Track::new("t2", ClipType::Video);
    t2.clips
        .push(Clip::new("clip-2", "asset-2", 0, frames as i32));
    tl.tracks.push(t1);
    tl.tracks.push(t2);

    let mut manifest = MediaManifest::new();
    manifest.entries.push(external_entry(
        "asset-1", &src_a, w as i32, h as i32, fps as f64,
    ));
    manifest.entries.push(external_entry(
        "asset-2", &src_b, w as i32, h as i32, fps as f64,
    ));

    let size = RenderSize::new(w, h);
    let Some(mut rl) = try_render_loop(tl, &manifest, size) else {
        return;
    };

    // Both clips are active at frame 0 → two concurrent streams; the composite
    // must come back with real content (no panic, no all-black).
    let composed = render_until_content(&mut rl, 0, w, h)
        .expect("two-track composite should render non-black within the warm-up budget");
    assert!(composed.iter().any(|&b| b != 0));
}

/// The threaded `PlaybackEngine` end-to-end: spawn it over a real GPU + ffmpeg
/// with an `InstantClock` and in-memory sink/emitter, let the wall clock advance
/// the playhead, and assert frames + the playhead reach the traits before `stop`
/// joins the render thread. Covers the thread loop the RenderLoop tests don't.
#[test]
fn playback_engine_thread_streams_frames_to_sink_and_emitter() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let src = dir.path().join("src.mp4");
    let (w, h, fps, frames) = (320u32, 240u32, 10u32, 12u32);
    if !make_video(&src, w, h, fps, frames, 0) {
        eprintln!("skip: could not generate fixture media");
        return;
    }

    let mut tl = Timeline::new();
    tl.fps = fps as i32;
    let mut track = Track::new("t1", ClipType::Video);
    track
        .clips
        .push(Clip::new("clip-1", "asset-1", 0, frames as i32));
    tl.tracks.push(track);
    let mut manifest = MediaManifest::new();
    manifest.entries.push(external_entry(
        "asset-1", &src, w as i32, h as i32, fps as f64,
    ));

    let size = RenderSize::new(w, h);
    // Skip when no GPU adapter (the engine thread would otherwise just exit
    // internally and the assertions below couldn't distinguish that from a bug).
    if try_render_loop(tl.clone(), &manifest, size).is_none() {
        return;
    }

    let (sizes, media) = project_media(&manifest, &None);
    let text = project_text(&tl);

    let frame_count = Arc::new(AtomicUsize::new(0));
    let last_emitted = Arc::new(AtomicI32::new(-1));

    struct CountingSink(Arc<AtomicUsize>);
    impl FrameSink for CountingSink {
        fn push_frame(&self, _frame: &DecodedFrame) {
            self.0.fetch_add(1, Ordering::Relaxed);
        }
    }
    struct RecordingEmitter(Arc<AtomicI32>);
    impl PlayheadEmitter for RecordingEmitter {
        fn emit(&self, frame: i32) {
            self.0.store(frame, Ordering::Relaxed);
        }
    }

    let clock: Arc<dyn PlaybackClock> = Arc::new(InstantClock::new(0));
    let sink: Arc<dyn FrameSink> = Arc::new(CountingSink(frame_count.clone()));
    let emitter: Arc<dyn PlayheadEmitter> = Arc::new(RecordingEmitter(last_emitted.clone()));

    let engine = PlaybackEngine::spawn(tl, media, text, sizes, size, clock, sink, emitter)
        .expect("engine spawns");
    // The wall clock advances the playhead; give the render thread time to produce
    // a few frames, then stop (which joins the thread).
    sleep(Duration::from_millis(600));
    engine.stop();

    assert!(
        frame_count.load(Ordering::Relaxed) > 0,
        "the engine thread produced no frames"
    );
    assert!(
        last_emitted.load(Ordering::Relaxed) >= 0,
        "the engine thread emitted no playhead frame"
    );
}
